### ISSUE TITLE
(Suggestion) Weapon Mods?

### ISSUE THREAD

**Issue by Jboby1** [Smashman/mods.tf#19]
This site has been around for several years already, so I imagine that if you were planning this you would've done so already, but could you include a section for weapon model replacements? 

Sure, Gamebanana has a wide selection of those types of mods, but ever since the Facepunch Emporium and tf2mods.net went down, taking a wide breadth of exclusive mods with them, the weapon reskin scene hasn't felt the same since. It'd be nice to regain some of that variety.

**Comment by Smashman** [comment]
Due to only cosmetic items supporting the gold star zip format, mods.tf will never support weapon mods.

The gold star zip format is necessary to ensure that the system can pick out the necessary parts to rename and repackage.

Let me know if you have any further questions, but I will close this issue.

Thanks

**Comment by AtomicTEM** [comment]
What is the Gold star zip format? And why do only cosmetics support that?
